language: ruby
rvm:
  - 2.3.0
before_script:
  - curl https://raw.githubusercontent.com/dkniffin/dummy-qa/master/bin/before-test.sh -o /tmp/before-test.sh
  - bash /tmp/before-test.sh
script:
  - bundle exec rubocop
  - bundle exec rspec
  - curl -s https://raw.githubusercontent.com/dkniffin/dummy-qa/master/bin/test.sh -o /tmp/test.sh
  - bash /tmp/test.sh
