default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dummy_backend_development

test:
  <<: *default
  database: dummy_backend_test

production:
  <<: *default
  database: dummy_backend_production
  username: dummy-backend
  password: <%= ENV['dummy_backend_DATABASE_PASSWORD'] %>
